default: &default
  adapter: postgresql
  encoding: unicode
  # Se for rodar localmente sem docker, trocar o host
  # host: localhost
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: adm_project_development


test:
  <<: *default
  database: adm_project_test
