development:
  adapter: postgresql
  encoding: utf8
  database: adm_project_development
  pool: 3
  username: postgres
  password:
  #host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: adm_project_test
  pool: 3
  username: postgres
  password:
  #host: localhost
